{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana
  labels:
    app: grafana
data:
  # username: admin
  # password: password
  admin-username: YWRtaW4=
  admin-password: cGFzc3dvcmQ=
{{- end }}