{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dataflow-grafana.ms.example.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:717603026805:certificate/d7ffdc20-63f4-44cc-9961-94ebce6bd472
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3000
{{- end }}