apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scdf.fullname" . }}-server
  labels:
    app: {{ template "scdf.name" . }}
    component: server
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yaml: |-
    management:
      endpoint:
        health:
          show-details: ALWAYS
    spring:
      cloud:
        dataflow:
          applicationProperties:
            stream:
              management:
                metrics:
                  export:
                    prometheus:
                      enabled: true
                endpoints:
                  web:
                    exposure:
                      include: 'prometheus,info,health'
              spring:
                cloud:
                  streamapp:
                    security:
                      enabled: false
          grafana-info:
            url: {{ .Values.monitoring.grafanaUrl }}
          task:
            platform:
              kubernetes:
                accounts:
                  {{ .Values.server.platformName }}:
                    limits:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{ .Values.deployer.resourceLimits.cpu }}
      datasource:
        url: 'jdbc:mysql://www.example.com:3306/dataflow'
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: Ch4ngeme!
        testOnBorrow: true
        validationQuery: "SELECT 1"
