apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scdf.fullname" . }}-skipper
  labels:
    app: {{ template "scdf.name" . }}
    component: skipper
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  application.yaml: |-
    spring:
      cloud:
        skipper:
          server:
            enableLocalPlatform: false
            platform:
              kubernetes:
                accounts:
                  {{ .Values.skipper.platformName }}:
                    {{- if .Values.rabbitmq.enabled}}
                    environmentVariables: 'SPRING_RABBITMQ_HOST=${{ printf "{" }}{{ template "scdf.envrelease" . }}_RABBITMQ_SERVICE_HOST},SPRING_RABBITMQ_PORT=${{ printf "{" }}{{ template "scdf.envrelease" . }}_RABBITMQ_SERVICE_PORT_AMQP},SPRING_RABBITMQ_USERNAME={{ .Values.rabbitmq.rabbitmqUsername }},SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}'
                    {{- else if .Values.kafka.enabled}}
                    environmentVariables: 'SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS={{ .Values.kafka.brokers }},SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES={{ .Values.kafka.zookeeper.nodes }}'
                    {{- end}}
                    limits:
                      memory: {{ .Values.deployer.resourceLimits.memory }}
                      cpu: {{ .Values.deployer.resourceLimits.cpu }}
                    readinessProbeDelay: {{ .Values.deployer.readinessProbe.initialDelaySeconds }}
                    livenessProbeDelay: {{ .Values.deployer.livenessProbe.initialDelaySeconds }}
                    podAnnotations: 'prometheus.io/path:/actuator/prometheus,prometheus.io/port:8080,prometheus.io/scrape:true'
      datasource:
        url: 'jdbc:mysql://www.example.com:3306/skipper'
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: Ch4ngeme!
        testOnBorrow: true
        validationQuery: "SELECT 1"